# Generated by Django 5.2 on 2025-11-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chili_app', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bottled', 'Bottled Chili Garlic'), ('meal', 'Chili Garlic Meals'), ('snack', 'Snack'), ('drink', 'Drinks')], default='bottled', max_length=20),
        ),
    ]
