# Generated by Django 5.2 on 2025-11-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chili_app', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
