# Generated by Django 5.2 on 2025-11-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chili_app', '0004_product_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tagline',
        ),
    ]
