# Generated by Django 5.2 on 2025-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chili_app', '0005_remove_product_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addons',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
